return {
    "christoomey/vim-tmux-navigator",
    enabled = false,
    lazy = false,
    cmd = {
        "TmuxNavigateLeft",
        "TmuxNavigateDown",
        "TmuxNavigateUp",
        "TmuxNavigateRight",
        "TmuxNavigatePrevious",
    },
    keys = {
        { "<c-h>",  "<cmd><C-U>TmuxNavigateLeft<cr>" },
        { "<c-j>",  "<cmd><C-U>TmuxNavigateDown<cr>" },
        { "<c-l>",  "<cmd><C-U>TmuxNavigateRight<cr>" },
        { "<c-\\>", "<cmd><C-U>TmuxNavigatePrevious<cr>" },
        { "<c-k>",  "<cmd><C-U>TmuxNavigateUp<cr>" },
    },
    -- vim.keymap.set("n", "C-h", ":TmuxNavigateLeft<CR>"),
    -- vim.keymap.set("n", "C-j", ":TmuxNavigateDown<CR>"),
    -- vim.keymap.set("n", "C-k", ":TmuxNavigateUp<CR>"),
    -- vim.keymap.set("n", "C-l", ":TmuxNavigateRight<CR>"),
    -- keys = {
    -- 	{ "<C-h>", "<cmd><C-U>TmuxNavigateLeft<cr>" },
    -- 	{ "<C-j>", "<cmd><C-U>TmuxNavigateDown<cr>" },
    -- 	{ "<C-k>", "<cmd><C-U>TmuxNavigateUp<cr>" },
    -- 	{ "<C-l>", "<cmd><C-U>TmuxNavigateRight<cr>" },
    -- 	{ "<C-\\>", "<cmd><C-U>TmuxNavigatePrevious<cr>" },
    -- },
}
